### ISSUE TITLE
Buckets automatically deleted after some time

### ISSUE THREAD

**Issue by hackersthan** [AlecBlance/S3BucketList#22]
Hello @AlecBlance 

Buckets are automatically deleted after some time.

Thank You,
Sachin

**Comment by AlecBlance** [comment]
Hi @hackersthan !

I believe this has been fixed in v3.0.1. What version are you currently in?

**Comment by hackersthan** [comment]
Hello @AlecBlance 

Sorry i'm using v3.0.1, but in v3.0.1 everything is find.

Thank You,
Sachin

**Comment by hackersthan** [comment]
Hello @AlecBlance 

Just like v3.0.0, Bucket disappear after some time in v3.1.0 too.

Thank You,
Sachin

**Comment by AlecBlance** [comment]
I'll take a look at this again. I may have missed something. Thank you!

**Comment by AlecBlance** [comment]
Hello @hackersthan ,

I really appreciate your help here. I found the issue, and I fixed it accordingly. I will publish it in the chrome store right now, and hopefully we'll have the v3.1.1 there soon. But, you can download the [release](https://github.com/AlecBlance/S3BucketList/releases/tag/v3.1.1) if you want to use it right away. 

Thanks,
Alec

**Comment by hackersthan** [comment]
Now it works perfect, love this project. <3

**Comment by AlecBlance** [comment]
Thanks! If you have any suggestions, let me know.
