### ISSUE TITLE
Once an error always error.

### ISSUE THREAD

**Issue by hackersthan** [AlecBlance/S3BucketList#28]
Hello @AlecBlance 

I don't know that this is a bug or not, but i really want you to know about this.

**request**
```
https://bucket.s3.amazonaws.com/path?parameter=value
```

**response**
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>7200</X-Amz-Expires>
<Expires>2024-10-03T18:37:54Z</Expires>
<ServerTime>2024-10-26T03:56:41Z</ServerTime>
<RequestId>ZEV3GDHQN0XXXXX</RequestId>
<HostId>9E5rRxxxxxxy1rEe+cWd7gqZQITI8Dzmy7E5KPfpRHxRrcsAgEcKEyh0xxxxxxxxxxxxxwi0=</HostId>
</Error>
```

`s3bucketlist` add this bucket into `error` section.  
But if the main bucket list is open like this

**request**
```
https://bucket.s3.amazonaws.com
```

**response**
```xml
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>bucket-name</Name>
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>false</IsTruncated>
<Contents>
<Key>file.mp4</Key>
<LastModified>2024-09-29T16:37:06.000Z</LastModified>
<ETag>"bf2d2748564839dc8xxxxxxxxxxxx"</ETag>
<Size>115615730</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
<Contents>
```

`S3BucketList` will not put this bucket into good, So once a error always a error. Its not rechecking same host. 

It must check two requests, one main url and second host only.
```
https://bucket.s3.amazonaws.com/path?parameter=value
https://bucket.s3.amazonaws.com
```

Again i'm not sure about this, but i really want to share it with you.
Thank You,
Sachin

**Comment by AlecBlance** [comment]
Thank you @hackersthan ,

I'm not sure if this is a bug due to this implementation. 
https://github.com/AlecBlance/S3BucketList/blob/c64d4ece52c31b711dee9ca2c7bcaf6eef8d7082/src/lib/recorder.ts#L79

I'm extracting the hostname instead of the whole url, so having path, and parameters won't affect the check. But, I'll keep this open in case anyone (even me) experienced the same issue.

**Comment by hackersthan** [comment]
Yes you are right, i tried it by removing from error, and direct open host. It still put this in error, don't know why.
Not a big problem, because we should check all the buckets including good, bad, and error.

I'm self closing this issue.

**Comment by AlecBlance** [comment]
Hi @hackersthan, I'm just curious, what's the result when you access this `https://bucket.s3.amazonaws.com/?acl`?

**Comment by hackersthan** [comment]
Hello @AlecBlance 

Without removing from `error` section, nothing happens it stay in error.
By removing from `error` section then directly access `https://bucket.s3.amazonaws.com/?acl` it shows in `error` section again. 

I observe some things,
1. access this bucket `xxx-xxx-xxx-xxx.s3.ap-south-1.amazonaws.com` directory list open, put it into `error` section.
2. access same bucket `xxx-xxx-xxx-xxx.s3.amazonaws.com` directory list open, put it into `error` section.
3. access another bucket `xxx-xxx-xxx.s3.amazonaws.com` directory list open, put into `good` section

might be problem with `-` ?


One more thing by requesting `https://s3.amazonaws.com/bucket-upload`, it put only one buckets into `error` section 
`https://s3.amazonaws.com/bucket-upload`. [in `error` section because of `PermanentRedirect`.]

**Comment by AlecBlance** [comment]
Thank you for these valuable information, @hackersthan ! I'll test all these cases. 

When opening the `https://bucket.s3.amazonaws.com/?acl` did it say `AccessDenied` as well in the browser, not in the extension?

**Comment by AlecBlance** [comment]
I think I got the issue now. Thanks for the help @hackersthan . The next version should fix this issue.

**Comment by hackersthan** [comment]
> Thank you for these valuable information, @hackersthan ! I'll test all these cases.
> 
> When opening the `https://bucket.s3.amazonaws.com/?acl` did it say `AccessDenied` as well in the browser, not in the extension?

I observe that `?acl` does not have any impact. For this case permission are open still `s3bucketlist` put it into `error` section.



> I think I got the issue now. Thanks for the help @hackersthan . The next version should fix this issue.

I hope you will fix this issue soon.

Best Regards,
Sachin

**Comment by AlecBlance** [comment]
@hackersthan [v3.1.2](https://github.com/AlecBlance/S3BucketList/releases/tag/v3.1.2) should fix this issue. As for `PermanentRedirect` that you mentioned, I'll need to investigate on that one further. 

Again, thank you so much for the help! 🎉

**Comment by hackersthan** [comment]
Hello @AlecBlance
Now its working as intended.
