### ISSUE TITLE
Delete button doesn't work always as intended

### ISSUE THREAD

**Issue by moashxer** [AlecBlance/S3BucketList#8]
**Describe the bug**
So there are over 50+ captured buckets, I wanted delete only few specific buckets by clicking 'Delete' button however it works sometimes and other times even after multiple click it doesn't work

**To Reproduce**
1. see the captured multiple buckets which seems not vulnerable
2. Click on 'Delete', and check if the bucket decreases  

**Expected behavior**
Can't delete buckets manually one by one,  
 - Browser: Firefox ESR
 - Version [78.15.0]

**Comment by moashxer** [comment]
Also do you mind what this is,
Error
Error getting permissions

Access to <ListBucketResult>
True

is it vulnerable or should I ignore it

**Comment by AlecBlance** [comment]
Sorry, it took me sometime. I've been busy with school. I'll update this

**Comment by AlecBlance** [comment]
I just checked this in the new v2.1 of S3BucketList and I can't reproduce this issue. 
Also please bear in mind that this extension will just help you in your bucket discovery and will not show you if it is vulnerable. Just for your information, the 
"Error getting permissions" usually means that we cannot access the bucket's access control list. It probably needs authentication of some sort. 
However, the "Access to" & "True" are new to me. If you can provide me the s3 bucket link that shows this result. I will gladly look at this issue again. Please feel free to reopen this issue anytime.
