### ISSUE TITLE
Firefox addons link remove

### ISSUE THREAD

**Issue by s41n1k** [AlecBlance/S3BucketList#9]
HI,
The firefox add-ons link is broken, please update a new link.
[Broken link](https://addons.mozilla.org/en-US/firefox/addon/s3-bucket-list/)
Thank you.

**Comment by AlecBlance** [comment]
Sorry, it took me sometime. I've been busy with school. I'll update this

**Comment by AlecBlance** [comment]
I just knew that Manifest v3 will be the standard manifest version this 2023. A lot has changed. 
Firefox will soon implement Manifest v3 and seeing that there isn't much information, I transferred to Chrome instead. 
I will be porting this to Firefox once they support the same service worker as Chrome's. Thanks for raising this! 

My latest commit makes this extension work in Chrome. 
[67446ac](https://github.com/AlecBlance/S3BucketList/commit/67446acc4ba993c0576bb55188359005ad7b81c3)
